<!DOCTYPE html>

<html lang="fr">
    <head>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="./assets/styles/css/common.css">
        <link rel="stylesheet" href="./assets/styles/css/home.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet">
            <title>Yepify - Accueil</title>
    </head>
    <body>
        <nav>
            <a href="./">Accueil</a>
            <a href="nos-tarifs">Tarifs</a>
        </nav>
        <main>
            <section class="titre">
                <h1>Yepify</h1>
                <p>Les meilleurs Yep, partout, tout le temps.</p>
            </section>

            <section class="container-column content">
                <div class="container display-content">
                    <div>
                        <p>Yeppy Yeah</p>
                        <p>I'm feeling Yep</p>
                    </div>
                    <img class="tree" src="./img/tree.png" alt="Image de couché de soleil au bord de mer avec un arbre"/>
                </div>
                <div>
                    <div>
                        <img class="icons" src="./img/equalizer.png" alt="Icône de volume"/>
                        <p>Yeppin' on a prayer</p>
                    </div>
                    <div>
                        <img class="icons" src="./img/play.png" alt="Icône play"/>
                        <p>Yep it be</p>
                    </div>
                    <div>
                        <img class="icons" src="./img/play.png" alt="Icône play"/>
                        <p>Yeppin on the dock of the bay</p>
                    </div>
                    <div>
                        <img class="icons" src="./img/play.png" alt="Icône play"/>
                        <p>Because the yep</p>
                    </div>
                    <div>
                        <img class="icons" src="./img/play.png" alt="Icône play"/>
                        <p>Leaving Las Yepas</p>
                    </div>
                    <div>
                        <img class="icons" src="./img/play.png" alt="Icône play"/>
                        <p>Enter Yepman</p>
                    </div>
                    <div>
                        <img class="icons" src="./img/play.png" alt="Icône play"/>
                        <p>Fear of the yep</p>
                    </div>
                </div>
            </section>
        </main>
    </body>
</html>
